---
apiVersion: "networking.istio.io/v1alpha3"
kind: "Gateway"
metadata:
  labels:
    app: {{ template "docs-littleman-co.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "docs-littleman-co.fullname" . }}
spec:
  selector:
    # use Istio default gateway implementation
    istio: "ingressgateway"
  servers:
  - port:
      number: 80
      name: {{ template "docs-littleman-co.fullname" . }}-http
      protocol: "HTTP"
    hosts:
    - "docs.littleman.co"
    tls:
      # sends 301 redirect for http requests
      httpsRedirect: true
  - port:
      number: 443
      name: {{ template "docs-littleman-co.fullname" . }}-https
      protocol: "HTTPS"
    tls:
      mode: "SIMPLE"
      serverCertificate: "/etc/istio/ingressgateway-certs/docs.crt"
      privateKey: "/etc/istio/ingressgateway-certs/docs.key"
    hosts:
    - "docs.littleman.co"

