---
kind: "pipeline"
name: "docs-web"

steps:
  - name: "antora"
    environment:
      DOCSEARCH_ENABLED: true
      DOCSEARCH_ENGINE: "lunr"
      NODE_PATH: "./src/js:/usr/local/lib/node_modules:./node_modules"
    image: "quay.io/sitewards/antora"
    commands:
      - "npm install"
      - "node node_modules/.bin/antora --generator 'generator' site.yml"
  - name: "container"
    image: "plugins/gcr"
    settings:
      repo: "littleman-co/docs-littleman-co"
      dockerfile: "build/container/Dockerfile"
      json_key:
        from_secret: "GOOGLE_SERVICE_ACCOUNT"

---
kind: "pipeline"
name: "deployment"

steps:
  - name: "deploy"
    image: "quay.io/littlemanco/helm"
    environment:
      B64_GOOGLE_SERVICE_ACCOUNT:
        from_secret: "B64_GOOGLE_SERVICE_ACCOUNT"
      GOOGLE_APPLICATION_CREDENTIALS: "/tmp/.google-service-account.json"
      GOOGLE_PROJECT_NAME: "littleman-co"
      GOOGLE_PROJECT_REGION: "europe-west1-d"
      GOOGLE_GKE_CLUSTER_NAME: "littleman-co"
      KUBERNETES_NAMESPACE: "docs-littleman-co"
    commands:
      - "echo $B64_GOOGLE_SERVICE_ACCOUNT | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS"
      - "gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS"
      - "gcloud config set project $GOOGLE_PROJECT_NAME"
      - "gcloud container clusters get-credentials --zone $GOOGLE_PROJECT_REGION $GOOGLE_GKE_CLUSTER_NAME"
      - "helm upgrade --install --namespace docs-littleman-co docs-littleman-co deploy/helm"

trigger:
  branch:
    - "master"

depends_on:
  - "docs-web"
