---
site:
  title: "docs.littleman.co"
  url: "https://docs.littleman.co"
  start_page: "business::index.adoc"
content:
  sources:
    - url: "."
      branches: "HEAD"
      start_path: "business"
    - url: "."
      branches: "HEAD"
      start_path: "development"

ui:
  bundle:
    url: "https://gitlab.com/g.grossetie/antora-ui-default/-/jobs/artifacts/lunr-integration/raw/build/ui-bundle.zip?job=bundle-dev"
    snapshot: true
  supplemental_files: ./src/antora-ui/supplemental-ui

asciidoc:
  extensions:
    - '/lib/asciidoctor-plantuml/adapter.js'
  attributes:
    plantuml-server-url: 'http://www.plantuml.com/plantuml'
    plantuml-fetch-diagram: true

output:
  dir: web
